# Generated by Django 3.2.9 on 2021-12-21 14:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Health',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('pcity', models.CharField(max_length=100)),
                ('ptemp', models.DecimalField(decimal_places=1, max_digits=50)),
                ('pupdate', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Distribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dpno', models.CharField(max_length=100)),
                ('dno', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('pending', '待确认'), ('confirmed', '已确认')], max_length=30)),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deliveryman.health')),
            ],
        ),
    ]
