# Generated by Django 2.2.5 on 2021-12-07 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('companyname', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='SalerInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salerid', models.CharField(max_length=200)),
                ('orderid', models.CharField(max_length=200)),
                ('companyid', models.CharField(max_length=200)),
            ],
        ),
    ]
