# Generated by Django 2.2.5 on 2021-12-20 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SalerPlaceOrder', '0002_company_companyid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='companyid',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='salerinfo',
            name='companyid',
            field=models.CharField(default=0, max_length=200),
        ),
    ]
