# Generated by Django 3.2.9 on 2021-12-21 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Dno', models.CharField(max_length=100)),
                ('Dvalue', models.DecimalField(decimal_places=2, max_digits=50)),
                ('Tno', models.CharField(max_length=100)),
                ('Sno', models.CharField(max_length=100)),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', '待确认'), ('confirmed', '已确认')], max_length=30)),
            ],
        ),
    ]
