# Generated by Django 3.2.9 on 2021-12-12 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=25, unique=True)),
                ('password', models.CharField(max_length=25)),
                ('utype', models.CharField(max_length=10)),
                ('companyname', models.CharField(max_length=225)),
                ('registerid', models.CharField(max_length=25)),
                ('address', models.CharField(max_length=225)),
                ('tel', models.CharField(max_length=11)),
                ('email', models.EmailField(max_length=25)),
                ('registerdate', models.DateField(auto_now_add=True)),
                ('agreement', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
