# Generated by Django 3.2.9 on 2021-12-12 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newuser',
            name='companyname',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='newuser',
            name='password',
            field=models.CharField(max_length=255),
        ),
    ]
