# Generated by Django 3.2.9 on 2021-12-22 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newuser',
            name='tel',
            field=models.CharField(max_length=128),
        ),
    ]
