# Generated by Django 3.2.9 on 2021-12-16 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0002_auto_20211212_0939'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newuser',
            name='agreement',
        ),
        migrations.AlterField(
            model_name='newuser',
            name='address',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='newuser',
            name='username',
            field=models.CharField(max_length=128, unique=True),
        ),
        migrations.AlterField(
            model_name='newuser',
            name='utype',
            field=models.CharField(max_length=128),
        ),
    ]
