# Generated by Django 2.2.5 on 2021-12-23 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PathVisualization', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='covid19',
            new_name='covid',
        ),
        migrations.RenameModel(
            old_name='Logistics_Location',
            new_name='Location',
        ),
    ]
