# Generated by Django 2.2.5 on 2021-12-23 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PathVisualization', '0002_auto_20211223_1518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='covid',
            name='date',
            field=models.DateTimeField(max_length=6),
        ),
    ]
