# Generated by Django 2.2.5 on 2021-12-25 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PathVisualization', '0003_auto_20211223_1520'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Location',
            new_name='GeographicInformation',
        ),
        migrations.RenameModel(
            old_name='covid',
            new_name='PandemicInformation',
        ),
    ]
