# Generated by Django 3.2.7 on 2022-01-05 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PathVisualization', '0005_auto_20211226_1530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pandemicinformation',
            name='id',
            field=models.AutoField(max_length=32, primary_key=True, serialize=False, unique=True),
        ),
    ]
