# Generated by Django 3.2.9 on 2021-12-22 08:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryInformationManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='OrderInformation',
            fields=[
                ('ono', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('otime', models.DateField()),
                ('ovalue', models.DecimalField(decimal_places=2, max_digits=8)),
                ('otype', models.CharField(max_length=64)),
                ('onum', models.IntegerField()),
                ('sellername', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sellernames', to=settings.AUTH_USER_MODEL)),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usernames', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DeliveryInformation',
            fields=[
                ('dno', models.CharField(max_length=128, primary_key=True, serialize=False, unique=True)),
                ('dvalue', models.DecimalField(decimal_places=10, max_digits=25, null=True)),
                ('dtrans', models.CharField(max_length=128)),
                ('dsetime', models.DateField(max_length=128, null=True)),
                ('dretime', models.DateField(max_length=128, null=True)),
                ('is_checked', models.BooleanField(default=False)),
                ('sno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='DeliveryInformation_NewUser_seller', to=settings.AUTH_USER_MODEL)),
                ('tno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='DeliveryInformation_NewUser_log', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
