# Generated by Django 3.2.9 on 2021-12-26 04:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RateSeller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quality', models.DecimalField(decimal_places=1, max_digits=2, null=True)),
                ('price', models.DecimalField(decimal_places=1, max_digits=2, null=True)),
                ('look', models.DecimalField(decimal_places=1, max_digits=2, null=True)),
                ('delivery', models.DecimalField(decimal_places=1, max_digits=2, null=True)),
                ('service', models.DecimalField(decimal_places=1, max_digits=2, null=True)),
                ('sellername', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rateforseller', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RateDelivComp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('speed', models.DecimalField(decimal_places=1, max_digits=2, null=True)),
                ('package', models.DecimalField(decimal_places=1, max_digits=2, null=True)),
                ('perfection', models.DecimalField(decimal_places=1, max_digits=2, null=True)),
                ('service', models.DecimalField(decimal_places=1, max_digits=2, null=True)),
                ('timely_feedback', models.DecimalField(decimal_places=1, max_digits=2, null=True)),
                ('compname', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rateforcompany', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderInformation',
            fields=[
                ('ono', models.CharField(max_length=32, primary_key=True, serialize=False, unique=True)),
                ('otime', models.DateField()),
                ('ovalue', models.DecimalField(decimal_places=2, max_digits=8)),
                ('otype', models.CharField(max_length=64)),
                ('onum', models.IntegerField()),
                ('platformname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='platformnames', to=settings.AUTH_USER_MODEL)),
                ('sellername', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sellernames', to=settings.AUTH_USER_MODEL)),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usernames', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DeliveryInformation',
            fields=[
                ('dno', models.CharField(max_length=32, primary_key=True, serialize=False, unique=True)),
                ('dvalue', models.DecimalField(decimal_places=2, max_digits=25, null=True)),
                ('dtrans', models.CharField(max_length=128)),
                ('dsetime', models.DateField(max_length=128, null=True)),
                ('dretime', models.DateField(max_length=128, null=True)),
                ('is_checked', models.BooleanField(default=False)),
                ('order_information', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.orderinformation')),
                ('sno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='DeliveryInformation_NewUser_seller', to=settings.AUTH_USER_MODEL)),
                ('tno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='DeliveryInformation_NewUser_log', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
