# Generated by Django 3.2.9 on 2021-12-21 09:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderInformation',
            fields=[
                ('ono', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('otime', models.DateField()),
                ('ovalue', models.DecimalField(decimal_places=2, max_digits=8)),
                ('otype', models.CharField(max_length=64)),
                ('onum', models.IntegerField()),
                ('sellername', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sellernames', to=settings.AUTH_USER_MODEL)),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usernames', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
