# Generated by Django 3.2.9 on 2022-01-14 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeographicTransformation',
            fields=[
                ('dloc', models.CharField(max_length=200, primary_key=True, serialize=False, unique=True)),
                ('dlat', models.DecimalField(decimal_places=4, max_digits=25)),
                ('dlng', models.DecimalField(decimal_places=4, max_digits=25)),
            ],
        ),
    ]
