# Generated by Django 3.2.9 on 2022-01-13 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeographicInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dno', models.CharField(max_length=200)),
                ('dloc', models.CharField(max_length=200)),
                ('dupdate', models.DateTimeField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='PandemicInformation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('date', models.DateTimeField(max_length=6)),
                ('place', models.CharField(max_length=200)),
                ('number', models.CharField(max_length=200)),
            ],
        ),
    ]
