# Generated by Django 3.2.9 on 2021-12-22 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryinformation',
            name='dno',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
    ]
