# Generated by Django 3.2.9 on 2021-12-23 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryinformation',
            name='dvalue',
            field=models.DecimalField(decimal_places=2, max_digits=25, null=True),
        ),
    ]
