# Generated by Django 3.2.9 on 2021-12-26 12:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DistributionInformation',
            fields=[
                ('dpno', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('is_checked', models.BooleanField(default=False)),
                ('dno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='DistributionInformation_OrderNo', to='dashboard.deliveryinformation')),
                ('pno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='DistributionInformation_Deliverymanname', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CompanyStaff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='CompanyStaff_Staffname', to=settings.AUTH_USER_MODEL)),
                ('tno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='CompanyStaff_Companyname', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HealthInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pcity', models.CharField(max_length=100)),
                ('ptemp', models.DecimalField(decimal_places=1, max_digits=25)),
                ('pupdate', models.DateField(auto_now_add=True)),
                ('pno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='HealthInformation_Deliverymanname', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '员工健康信息表',
                'verbose_name_plural': '员工健康信息表',
                'unique_together': {('pno', 'pupdate')},
            },
        ),
    ]
