# Generated by Django 3.2.9 on 2021-12-21 15:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryInformationManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='DeliveryInformation',
            fields=[
                ('dno', models.CharField(max_length=128, primary_key=True, serialize=False, unique=True)),
                ('dvalue', models.DecimalField(decimal_places=10, max_digits=25, null=True)),
                ('dtrans', models.CharField(max_length=128)),
                ('dsetime', models.DateField(max_length=128, null=True)),
                ('dretime', models.DateField(max_length=128, null=True)),
                ('is_checked', models.BooleanField(default=False, null=True)),
                ('sno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='DeliveryInfo_NewUser_seller', to=settings.AUTH_USER_MODEL)),
                ('tno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='DeliveryInfo_NewUser_log', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
