# Generated by Django 3.2.7 on 2022-01-12 07:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
        ('dashboard', '0002_delete_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companystaff',
            name='pno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='CompanyStaff_Staffname', to='register.newuser'),
        ),
        migrations.AlterField(
            model_name='companystaff',
            name='tno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='CompanyStaff_Companyname', to='register.newuser'),
        ),
        migrations.AlterField(
            model_name='deliveryinformation',
            name='sno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='DeliveryInformation_NewUser_seller', to='register.newuser'),
        ),
        migrations.AlterField(
            model_name='deliveryinformation',
            name='tno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='DeliveryInformation_NewUser_log', to='register.newuser'),
        ),
        migrations.AlterField(
            model_name='distributioninformation',
            name='pno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='DistributionInformation_Deliverymanname', to='register.newuser'),
        ),
        migrations.AlterField(
            model_name='healthinformation',
            name='pno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='HealthInformation_Deliverymanname', to='register.newuser'),
        ),
        migrations.AlterField(
            model_name='orderinformation',
            name='platformname',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='platformnames', to='register.newuser'),
        ),
        migrations.AlterField(
            model_name='orderinformation',
            name='sellername',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sellernames', to='register.newuser'),
        ),
        migrations.AlterField(
            model_name='orderinformation',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usernames', to='register.newuser'),
        ),
        migrations.AlterField(
            model_name='ratedelivcomp',
            name='compname',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rateforcompany', to='register.newuser'),
        ),
        migrations.AlterField(
            model_name='rateseller',
            name='sellername',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rateforseller', to='register.newuser'),
        ),
    ]
