# Generated by Django 3.2.9 on 2021-12-21 15:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0002_deliveryinformation_deliveryinformationmanager'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryinformation',
            name='is_checked',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='deliveryinformation',
            name='sno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='DeliveryInformation_NewUser_seller', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='deliveryinformation',
            name='tno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='DeliveryInformation_NewUser_log', to=settings.AUTH_USER_MODEL),
        ),
    ]
