# Generated by Django 3.2.9 on 2022-01-14 10:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_geographicinformation_pandemicinformation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryinformation',
            name='order_information',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='doinfo', to='dashboard.orderinformation'),
        ),
    ]
