# Generated by Django 3.2.9 on 2021-12-22 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_alter_deliveryinformation_dno'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DeliveryInformationManager',
        ),
    ]
