# Generated by Django 3.2.7 on 2021-12-20 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20211220_2347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderbuyer',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
        migrations.AlterField(
            model_name='orderdelivcomp',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
        migrations.AlterField(
            model_name='orderebplat',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
        migrations.AlterField(
            model_name='orderseller',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
    ]
