# Generated by Django 3.2.7 on 2021-12-20 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_auto_20211220_2357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rateseller',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
